<script lang="ts">
  import { ShieldCheck, Scale, FileText, Lock, RefreshCcw } from 'lucide-svelte';
</script>

<svelte:head>
  <title>Terms & Conditions | Piyush Cafe</title>
  <meta name="description" content="Terms and Conditions compliant with Indian legal requirements." />
</svelte:head>

<div class="min-h-screen bg-[var(--color-bg)] py-12 px-4 sm:px-6 lg:px-8 text-[var(--color-text)]">
  <div class="max-w-4xl mx-auto glass-strong rounded-3xl p-8 md:p-12 animate-slide-up relative overflow-hidden">
    <!-- Decorative background glow -->
    <div class="absolute top-0 right-0 w-96 h-96 bg-[var(--color-brand)]/10 rounded-full blur-[100px] pointer-events-none"></div>
    <div class="absolute bottom-0 left-0 w-96 h-96 bg-[var(--color-brand)]/10 rounded-full blur-[100px] pointer-events-none"></div>

    <div class="relative z-10">
      <div class="flex items-center gap-4 mb-8 pb-8 border-b border-white/10">
        <div class="w-16 h-16 rounded-2xl bg-[var(--color-brand)]/10 flex items-center justify-center border border-[var(--color-brand)]/30 text-[var(--color-brand)]">
          <Scale size={32} />
        </div>
        <div>
          <h1 class="text-4xl font-display text-white mb-2">Terms & Conditions</h1>
          <p class="text-[var(--color-text-secondary)]">Last Updated: {new Date().toLocaleDateString('en-IN')}</p>
        </div>
      </div>

      <div class="prose prose-invert max-w-none space-y-8 prose-headings:text-white prose-headings:font-display prose-a:text-[var(--color-brand)]">
        
        <section class="bg-black/20 p-6 rounded-2xl border border-white/5">
          <h2 class="flex items-center gap-2 text-2xl mb-4 text-[var(--color-brand)]"><FileText size={24} /> 1. Introduction</h2>
          <p>
            Welcome to Piyush Cafe App ("Platform", "we", "our", "us"). These Terms and Conditions ("Terms") govern your access to and use of our website, mobile application, and digital table ordering services. 
          </p>
          <p>
            This document is an electronic record in terms of the <strong>Information Technology Act, 2000</strong> and rules thereunder as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>
        </section>

        <section class="bg-black/20 p-6 rounded-2xl border border-white/5">
          <h2 class="flex items-center gap-2 text-2xl mb-4 text-[var(--color-brand)]"><ShieldCheck size={24} /> 2. Eligibility & Registration</h2>
          <ul class="list-disc pl-6 space-y-2 text-[var(--color-text-secondary)]">
            <li>You must be at least 18 years of age to use the Platform, as per the <strong>Indian Contract Act, 1872</strong>.</li>
            <li>By using the Platform, you represent and warrant that you have the right, authority, and capacity to enter into this agreement.</li>
            <li>Certain features (like placing orders) may require you to provide accurate information (e.g., name, phone number, table number).</li>
          </ul>
        </section>

        <section class="bg-black/20 p-6 rounded-2xl border border-white/5">
          <h2 class="flex items-center gap-2 text-2xl mb-4 text-[var(--color-brand)]"><FileText size={24} /> 3. Ordering and Pricing</h2>
          <ul class="list-disc pl-6 space-y-2 text-[var(--color-text-secondary)]">
            <li>All items listed on the Platform are subject to availability.</li>
            <li>Prices listed on the Platform are in Indian Rupees (INR) and are exclusive of applicable taxes unless stated otherwise.</li>
            <li>The total order value will include the Food Cost, applicable Food GST (e.g., 5%), and a Platform Fee (with its respective GST), in compliance with the <strong>Consumer Protection (E-Commerce) Rules, 2020</strong>.</li>
          </ul>
        </section>

        <section class="bg-black/20 p-6 rounded-2xl border border-white/5">
          <h2 class="flex items-center gap-2 text-2xl mb-4 text-[var(--color-brand)]"><RefreshCcw size={24} /> 4. Payments, Cancellations & Refunds</h2>
          <ul class="list-disc pl-6 space-y-2 text-[var(--color-text-secondary)]">
            <li>Payments are processed securely via third-party payment gateways (e.g., PayU) conforming to RBI guidelines.</li>
            <li>Once an order is confirmed and sent to the kitchen, it cannot be cancelled by the user.</li>
            <li>If the restaurant is unable to fulfill your order due to unavailability, a full refund will be initiated to the original payment method within 5-7 business days.</li>
            <li>Refunds for failed transactions will be processed automatically by the payment gateway as per standard banking timelines.</li>
          </ul>
        </section>

        <section class="bg-black/20 p-6 rounded-2xl border border-white/5">
          <h2 class="flex items-center gap-2 text-2xl mb-4 text-[var(--color-brand)]"><Lock size={24} /> 5. Data Privacy</h2>
          <p class="text-[var(--color-text-secondary)]">
            Your privacy is important to us. The collection, storage, and processing of your personal data are governed by our Privacy Policy, which is designed to be compliant with the <strong>Digital Personal Data Protection Act, 2023 (DPDP Act)</strong> and the <strong>IT (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011</strong>. We implement reasonable security practices to protect your data.
          </p>
        </section>

        <section class="bg-black/20 p-6 rounded-2xl border border-white/5">
          <h2 class="flex items-center gap-2 text-2xl mb-4 text-[var(--color-brand)]"><Scale size={24} /> 6. Governing Law & Jurisdiction</h2>
          <p class="text-[var(--color-text-secondary)]">
            These Terms shall be governed by and constructed in accordance with the laws of India. Any disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the competent courts located in India.
          </p>
        </section>

        <section class="bg-black/20 p-6 rounded-2xl border border-white/5">
          <h2 class="text-2xl mb-4 text-[var(--color-brand)]">7. Contact & Grievance Officer</h2>
          <p class="text-[var(--color-text-secondary)]">
            In accordance with the Information Technology Act 2000 and rules made there under, the name and contact details of the Grievance Officer are provided below:
          </p>
          <div class="mt-4 p-4 bg-black/40 rounded-xl border border-white/10 text-sm font-mono text-gray-300">
            Email: metachasm@gmail.com / nit.uniyal@gmail.com<br/>
            Time: Mon - Sat (9:00 - 18:00)
          </div>
        </section>

      </div>
    </div>
  </div>
</div>

<style>
  :global(.prose p) {
    margin-bottom: 1rem;
    color: var(--color-text-secondary);
  }
</style>
